CREATE DATABASE ClaseUno
GO
USE ClaseUno
GO
CREATE TABLE Areas(
	ID BIGINT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(40) NOT NULL,
	Presupuesto MONEY NOT NULL CHECK( Presupuesto > 0 ),
	EMail VARCHAR(120) NOT NULL UNIQUE
)
GO
CREATE TABLE Empleados(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Apellido VARCHAR(100) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
	Genero CHAR NULL,
	IDArea BIGINT NOT NULL FOREIGN KEY REFERENCES Areas(ID),
    FechaNacimiento DATE null
)
GO